spring: 
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:E:\\sqlite\\levelDict.db
    username:
    password:
### sqlite需要自己配置连接方式
  jpa:
    database-platform: com.level.config.SQLiteDialect #自己配置的方言
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true